name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23li2aSOrV7kHXCgJq"
GITHUB_OWNER = "qicoka"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://yang-nav.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://yang-nav.pages.dev/"

